#!/bin/sh
printf 'Content-Type: application/javascript; charset=utf-8\r\n'
printf 'Cache-Control: no-store, no-cache, must-revalidate, max-age=0\r\n'
printf 'Pragma: no-cache\r\n'
printf 'Expires: 0\r\n'
printf 'X-Content-Type-Options: nosniff\r\n'
printf '\r\n'
cat /www/airvpn-native-ui.js